

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        files: \.md$
        exclude: __pycache__|\.pytest_cache

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: __pycache__|\.pytest_cache

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-pyproject]
        exclude: __pycache__|\.pytest_cache

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
      - id: pytest
        name: Run pytest
        entry: bash -c 'PYTHONPYCACHEPREFIX=/dev/null poetry run pytest --disable-warnings --cache-clear'
        language: system
        types: [python]
        exclude: __pycache__|\.pytest_cache
