repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        files: \.md$
        exclude: __pycache__|\.pytest_cache

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: __pycache__|\.pytest_cache

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-pyproject]
        exclude: __pycache__|\.pytest_cache

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: bash -c 'PYTHONPYCACHEPREFIX=/dev/null poetry run pytest --disable-warnings --cache-clear'
        language: system
        types: [python]
        exclude: __pycache__|\.pytest_cache

