repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        files: \.md$

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
      - name: black
        entry: black --config .blackrc
        language: system
        types: [python]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]

