name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Update lock file if needed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          poetry lock --no-update
          if ! git diff --exit-code --quiet poetry.lock; then
            git add poetry.lock
            git commit -m "Update poetry.lock to match pyproject.toml changes"
            git push origin main
          fi

      - name: Install dependencies
        run: poetry install

      - name: Run linting
        run: poetry run flake8

      - name: Run formatting check
        run: poetry run black --check .

      - name: Run tests
        run: PYTHONDONTWRITEBYTECODE=1 poetry run pytest
