name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run linting
        run: poetry run flake8

      - name: Run formatting check
        run: poetry run black --check .

      - name: Run tests
        run: PYTHONDONTWRITEBYTECODE=1 poetry run pytest
