name: Versioning

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Bump version and push tag
        id: bump_version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          poetry version patch
          NEW_VERSION=$(poetry version -s)
          git commit -am "Bump version to ${NEW_VERSION}"
          git tag "v${NEW_VERSION}"
          git push origin main --tags

      - name: Create major and minor version tags
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          MAJOR_VERSION=$(echo $NEW_VERSION | cut -d. -f1)
          MINOR_VERSION=$(echo $NEW_VERSION | cut -d. -f1-2)
          git tag -f "v${MAJOR_VERSION}"
          git tag -f "v${MINOR_VERSION}"
          git push origin --tags --force
