name: Versioning

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Update pip
        run: python -m pip install --upgrade pip
        
      - name: Install Poetry
        run: pip install poetry
        
      - name: Remove poetry.lock
        run: rm -f poetry.lock
        
      - name: Lock dependencies
        run: poetry lock
        
      - name: Install dependencies
        run: python -m poetry install
        
      - name: Bump version
        run: poetry version patch
        
      - name: Commit changes
        run: git config --global user.email && git config --global user.name && git add . && git commit -am "Bump version"
        
      - name: Push changes
        run: git push
        
            


